// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huuwojhwnvsdiroekziu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1dXdvamh3bnZzZGlyb2Vreml1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDY4MDIsImV4cCI6MjA2OTcyMjgwMn0.VZzE5Oq71mwG7U_F4tz-hUiCzaksJCzL6y9lpxNCK7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});